import os

try:
    import torch
except ImportError:
    torch = None

SEED = 42
DEVICE = "cuda" if torch is not None and torch.cuda.is_available() else "cpu"

DEFAULT_JOB_NAME = "demo"
DEFAULT_SPEAKER_ID = "spk_0"
SUFFIX = DEFAULT_JOB_NAME

INPUT_PATH = "./data/input"
OUTPUT_PATH = "./data/output"
TEST_OUTPUT_PATH = "./data/test"
JOB_OUTPUT_DIR = os.path.join(OUTPUT_PATH, SUFFIX)
TEMP_DIR = os.path.join(JOB_OUTPUT_DIR, "temp")
INPUT_VIDEO_EXTENSIONS = (".mp4", ".mov", ".mkv", ".avi", ".webm")

ORIGINAL_VIDEO_PATH = os.path.join(INPUT_PATH, f"video_{SUFFIX}.mp4")
ORIGINAL_AUDIO_PATH = os.path.join(TEMP_DIR, "original_extracted_audio.wav")
SPEAKER_REF_PATH = os.path.join(TEMP_DIR, "speaker_ref.wav")
VOCALS_PATH = os.path.join(TEMP_DIR, "vocals.wav")
VOCALS_PROCESSED = os.path.join(TEMP_DIR, "vocals_processed.wav")
BACKGROUND_PATH = os.path.join(TEMP_DIR, "background.wav")
FINAL_VOICE_PATH = os.path.join(JOB_OUTPUT_DIR, "final_dubbing.wav")
FINAL_MIX_PATH = os.path.join(JOB_OUTPUT_DIR, "final_mix.wav")
FINAL_VIDEO_PATH = os.path.join(JOB_OUTPUT_DIR, "final_video.mp4")
SEGMENTS_PATH = os.path.join(JOB_OUTPUT_DIR, "segments.json")
TRANSLATED_SEGMENTS_PATH = os.path.join(JOB_OUTPUT_DIR, "translated_segments.json")

MODEL_TTS_DIR = "./original_tts_model"
FINETUNED_TTS_DIR = "./models/finetuned_tts"

WHISPER_MODEL_NAME = os.getenv("WHISPER_MODEL_NAME", "small")
ASR_PROVIDER = os.getenv("ASR_PROVIDER", "local").strip().lower()
ASR_API_MODEL = os.getenv("ASR_API_MODEL", "whisper-large-v3").strip()
ASR_API_KEY_ENV = os.getenv("ASR_API_KEY_ENV", "GROQ_API_KEY").strip() or "GROQ_API_KEY"
ASR_BASE_URL = os.getenv("ASR_BASE_URL", "https://api.groq.com/openai/v1").strip()
ASR_TIMEOUT_SEC = int(os.getenv("ASR_TIMEOUT_SEC", "120"))

METRICS_WHISPER_MODEL_NAME = os.getenv("METRICS_WHISPER_MODEL_NAME", WHISPER_MODEL_NAME).strip()
METRICS_ASR_PROVIDER = os.getenv("METRICS_ASR_PROVIDER", "local").strip().lower()
METRICS_ASR_API_MODEL = os.getenv("METRICS_ASR_API_MODEL", ASR_API_MODEL).strip()
METRICS_ASR_API_KEY_ENV = os.getenv("METRICS_ASR_API_KEY_ENV", ASR_API_KEY_ENV).strip() or ASR_API_KEY_ENV
METRICS_ASR_BASE_URL = os.getenv("METRICS_ASR_BASE_URL", ASR_BASE_URL).strip()
METRICS_ASR_TIMEOUT_SEC = int(os.getenv("METRICS_ASR_TIMEOUT_SEC", str(ASR_TIMEOUT_SEC)))

DEMUCS_MODEL = os.getenv("DEMUCS_MODEL", "htdemucs")

ASR_SAMPLE_RATE = 16000
FINETUNE_SAMPLE_RATE = 22050
GAIN_INCREASE = 0.0
NOISE_REDUCE = True
PROP_DECREASE = 0.3
N_FFT = 512
HOP_LENGTH = 256

MAX_PAUSE_BETWEEN_SENTENCES = 0.3
MAX_AUDIO_LENGTH_FOR_REF = 15.0
SPEAKER_PROFILE_CLIPS = 5
SPEAKER_ROUTING_POOL_CLIPS = 12
SPEAKER_PROFILE_MIN_SEC = 2.0
SPEAKER_PROFILE_MAX_SEC = 10.0
SPEAKER_PROFILE_TARGET_SEC = 6.0
SPEAKER_PROFILE_MIN_TEXT_CHARS = 20
SPEAKER_PROFILE_PADDING_MS = 120
SPEAKER_PROFILE_MIN_GAP_SEC = 1.5

MT_MODEL_NAME = os.getenv("MT_MODEL_NAME", "facebook/nllb-200-distilled-1.3B")
MT_STRATEGY = os.getenv("MT_STRATEGY", "per-segment")
MT_SRC_LANG = os.getenv("MT_SRC_LANG", "eng_Latn")
MT_TGT_LANG = os.getenv("MT_TGT_LANG", "rus_Cyrl")
MT_MAX_SEGMENT_CHARS = int(os.getenv("MT_MAX_SEGMENT_CHARS", "150"))
MT_MAX_LENGTH = int(os.getenv("MT_MAX_LENGTH", "1024"))
MT_BATCH_SIZE = int(os.getenv("MT_BATCH_SIZE", "8"))
MT_MAX_CHUNK_CHARS = int(os.getenv("MT_MAX_CHUNK_CHARS", "800"))
MT_GEMINI_API_KEY_ENV = os.getenv("MT_GEMINI_API_KEY_ENV", "GEMINI_API_KEY")
MT_GEMINI_TEMPERATURE = float(os.getenv("MT_GEMINI_TEMPERATURE", "0.2"))
MT_GEMINI_MAX_OUTPUT_TOKENS = int(os.getenv("MT_GEMINI_MAX_OUTPUT_TOKENS", "512"))
MT_GEMINI_THINKING_BUDGET = int(os.getenv("MT_GEMINI_THINKING_BUDGET", "0"))
MT_GEMINI_TIMEOUT_SEC = int(os.getenv("MT_GEMINI_TIMEOUT_SEC", "120"))
MT_GEMINI_MIN_INTERVAL_SEC = float(os.getenv("MT_GEMINI_MIN_INTERVAL_SEC", "4.2"))
MT_GEMINI_MAX_RETRIES = int(os.getenv("MT_GEMINI_MAX_RETRIES", "6"))

LANGUAGE = os.getenv("LANGUAGE", "ru")
MAX_NEXT_START_SHIFT_SEC = float(os.getenv("MAX_NEXT_START_SHIFT_SEC", "0.25"))
MAX_SPEEDUP_FACTOR = float(os.getenv("MAX_SPEEDUP_FACTOR", "1.15"))
SPEEDUP_TAIL_PADDING_MS = int(os.getenv("SPEEDUP_TAIL_PADDING_MS", "120"))
MIN_PAUSE_SEGMENTS = float(os.getenv("MIN_PAUSE_SEGMENTS", "0.2"))
FADE_IN_OUT_MS = int(os.getenv("FADE_IN_OUT_MS", "50"))
CROSSFADE_MS = int(os.getenv("CROSSFADE_MS", "30"))
MAX_SHIFT_LEFT_SEC = float(os.getenv("MAX_SHIFT_LEFT_SEC", "0.5"))
XTTS_TEMPERATURE = float(os.getenv("XTTS_TEMPERATURE", "0.55"))
XTTS_LENGTH_PENALTY = float(os.getenv("XTTS_LENGTH_PENALTY", "1.0"))
XTTS_REPETITION_PENALTY = float(os.getenv("XTTS_REPETITION_PENALTY", "2.35"))
XTTS_TOP_K = int(os.getenv("XTTS_TOP_K", "50"))
XTTS_TOP_P = float(os.getenv("XTTS_TOP_P", "0.82"))

SMART_SYNC_ENABLED = os.getenv("SMART_SYNC_ENABLED", "1").strip().lower() not in {"0", "false", "no", "off"}
SMART_SYNC_PROVIDER = os.getenv("SMART_SYNC_PROVIDER", "groq").strip().lower()
SMART_SYNC_MODEL_NAME = os.getenv("SMART_SYNC_MODEL_NAME", "llama-3.3-70b-versatile")
SMART_SYNC_API_KEY_ENV = os.getenv(
    "SMART_SYNC_API_KEY_ENV",
    "GROQ_API_KEY" if SMART_SYNC_PROVIDER == "groq" else MT_GEMINI_API_KEY_ENV,
)
SMART_SYNC_BASE_URL = os.getenv(
    "SMART_SYNC_BASE_URL",
    "https://api.groq.com/openai/v1" if SMART_SYNC_PROVIDER == "groq" else "",
)
SMART_SYNC_TEMPERATURE = float(os.getenv("SMART_SYNC_TEMPERATURE", str(min(MT_GEMINI_TEMPERATURE, 0.3))))
SMART_SYNC_MAX_OUTPUT_TOKENS = int(os.getenv("SMART_SYNC_MAX_OUTPUT_TOKENS", "256"))
SMART_SYNC_TIMEOUT_SEC = int(os.getenv("SMART_SYNC_TIMEOUT_SEC", str(MT_GEMINI_TIMEOUT_SEC)))
SMART_SYNC_MIN_INTERVAL_SEC = float(
    os.getenv(
        "SMART_SYNC_MIN_INTERVAL_SEC",
        "2.2" if SMART_SYNC_PROVIDER == "groq" else str(MT_GEMINI_MIN_INTERVAL_SEC),
    )
)
SMART_SYNC_MAX_RETRIES = int(os.getenv("SMART_SYNC_MAX_RETRIES", str(MT_GEMINI_MAX_RETRIES)))
SMART_SYNC_MAX_REWRITES = int(os.getenv("SMART_SYNC_MAX_REWRITES", "1"))
SMART_SYNC_TRIGGER_SPEED_FACTOR = float(os.getenv("SMART_SYNC_TRIGGER_SPEED_FACTOR", "1.08"))
SMART_SYNC_MIN_FILL_RATIO = float(os.getenv("SMART_SYNC_MIN_FILL_RATIO", "0.82"))
SMART_SYNC_MIN_IMPROVEMENT_MS = int(os.getenv("SMART_SYNC_MIN_IMPROVEMENT_MS", "180"))
SMART_SYNC_ALLOW_LENGTHEN = os.getenv("SMART_SYNC_ALLOW_LENGTHEN", "1").strip().lower() not in {"0", "false", "no", "off"}
SMART_SYNC_ACCEPT_MIN_FILL_RATIO = float(os.getenv("SMART_SYNC_ACCEPT_MIN_FILL_RATIO", "0.8"))
SMART_SYNC_ACCEPT_MIN_TEXT_SIMILARITY = float(os.getenv("SMART_SYNC_ACCEPT_MIN_TEXT_SIMILARITY", "0.55"))
SMART_SYNC_ACCEPT_MIN_WORD_RATIO = float(os.getenv("SMART_SYNC_ACCEPT_MIN_WORD_RATIO", "0.66"))
SMART_SYNC_ACCEPT_MIN_TOKEN_PRECISION = float(os.getenv("SMART_SYNC_ACCEPT_MIN_TOKEN_PRECISION", "0.72"))
SMART_SYNC_ACCEPT_MIN_ASR_SCORE = float(os.getenv("SMART_SYNC_ACCEPT_MIN_ASR_SCORE", "0.9"))
SMART_SYNC_ACCEPT_MAX_ASR_DROP = float(os.getenv("SMART_SYNC_ACCEPT_MAX_ASR_DROP", "0.03"))

SEGMENT_ROUTING_ENABLED = True
SEGMENT_ROUTING_SHORT_SEC = 2.2
SEGMENT_ROUTING_MAX_REFS = 2
SEGMENT_ROUTING_MIN_SEC = 0.9
SEGMENT_ROUTING_MIN_WORDS = 3
SEGMENT_ROUTING_CONFIDENCE_MARGIN = 0.45

TTS_GROUPING_ENABLED = True
TTS_GROUPING_MAX_GAP_SEC = 0.6
TTS_GROUPING_MAX_SEGMENTS = 2
TTS_GROUPING_MAX_CHARS = int(os.getenv("TTS_GROUPING_MAX_CHARS", "180"))
TTS_GROUPING_MAX_DURATION_SEC = 8.5

ENABLE_TTS_CHEAP_TAIL_GUARD = True
TTS_CHEAP_TAIL_GUARD_MAX_SEGMENT_SEC = 3.2
TTS_CHEAP_TAIL_GUARD_MIN_OVERHANG_MS = 180
TTS_CHEAP_TAIL_GUARD_MIN_GAP_MS = 80
TTS_CHEAP_TAIL_GUARD_MIN_ISLAND_MS = 80
TTS_CHEAP_TAIL_GUARD_MAX_ISLAND_MS = 450
TTS_CHEAP_TAIL_GUARD_SEARCH_WINDOW_MS = 900
TTS_CHEAP_TAIL_GUARD_MAX_TRIM_MS = 700

ENABLE_TTS_BABBLE_GUARD = os.getenv("ENABLE_TTS_BABBLE_GUARD", "1").strip().lower() not in {"0", "false", "no", "off"}
TTS_BABBLE_GUARD_MODEL_NAME = os.getenv("TTS_BABBLE_GUARD_MODEL_NAME", "base")
TTS_BABBLE_GUARD_DEVICE = os.getenv("TTS_BABBLE_GUARD_DEVICE", "cpu")
TTS_BABBLE_GUARD_MAX_SEGMENT_SEC = float(os.getenv("TTS_BABBLE_GUARD_MAX_SEGMENT_SEC", "4.0"))
TTS_BABBLE_GUARD_MIN_GAP_MS = 80
TTS_BABBLE_GUARD_MIN_ISLAND_MS = 80
TTS_BABBLE_GUARD_MAX_ISLAND_MS = int(os.getenv("TTS_BABBLE_GUARD_MAX_ISLAND_MS", "450"))
TTS_BABBLE_GUARD_SEARCH_WINDOW_MS = int(os.getenv("TTS_BABBLE_GUARD_SEARCH_WINDOW_MS", "900"))
TTS_BABBLE_GUARD_MAX_TRIM_MS = int(os.getenv("TTS_BABBLE_GUARD_MAX_TRIM_MS", "700"))
TTS_BABBLE_GUARD_ANCHOR_WORDS = int(os.getenv("TTS_BABBLE_GUARD_ANCHOR_WORDS", "2"))
TTS_BABBLE_GUARD_MIN_SCORE_GAIN = float(os.getenv("TTS_BABBLE_GUARD_MIN_SCORE_GAIN", "0.08"))

ENABLE_TTS_ASR_RETRY = os.getenv("ENABLE_TTS_ASR_RETRY", "1").strip().lower() not in {"0", "false", "no", "off"}
TTS_ASR_RETRY_MODEL_NAME = os.getenv("TTS_ASR_RETRY_MODEL_NAME", "base")
TTS_ASR_RETRY_DEVICE = os.getenv("TTS_ASR_RETRY_DEVICE", "cpu")
TTS_ASR_RETRY_MAX_SEGMENT_SEC = 2.5
TTS_ASR_RETRY_ATTEMPTS = int(os.getenv("TTS_ASR_RETRY_ATTEMPTS", "2"))
TTS_ASR_RETRY_MIN_SCORE = float(os.getenv("TTS_ASR_RETRY_MIN_SCORE", "0.94"))

SHORT_SEGMENT_TAIL_TRIM_ENABLED = False
SHORT_SEGMENT_TAIL_TRIM_MIN_OVERHANG_MS = 280
SHORT_SEGMENT_TAIL_TRIM_MAX_MS = 500
SHORT_SEGMENT_TAIL_TRIM_MAX_RATIO = 0.22
SEGMENT_MATCHING_ENABLED = False
SEGMENT_MATCH_PADDING_MS = 120
SEGMENT_MATCH_STRENGTH = 0.7
SEGMENT_MATCH_MAX_DELTA_DB = 4.0
SEGMENT_MATCH_MIN_ACTIVE_RATIO = 0.35

THRESHOLD_COMPRESSION = -15.0
RATIO_COMPRESSION = 2.0
ATTACK_COMPRESSION = 25
RELEASE_COMPRESSION = 50
TARGET_DBFS = -15.0
REFERENCE_GAIN_OFFSET_DB = 3.0
MAX_SEGMENT_BOOST_DB = 6.0
MAX_SEGMENT_CUT_DB = 12.0
PEAK_CEILING_DBFS = -2.0
ENABLE_FINAL_COMPRESSION = False

VOICE_GAIN = -3.0
BACKGROUND_GAIN = -5.0
ORIGINAL_GAIN = -10.0

SUBTITLE_MODE = os.getenv("SUBTITLE_MODE", "soft")
SUBTITLE_USE_ORIGINAL = os.getenv("SUBTITLE_USE_ORIGINAL", "0").strip().lower() in {"1", "true", "yes", "on"}
SUBTITLE_ASS_FONT = os.getenv("SUBTITLE_ASS_FONT", "Arial")
SUBTITLE_ASS_FONT_SIZE = int(os.getenv("SUBTITLE_ASS_FONT_SIZE", "24"))

FINETUNE_DATA_ROOT = "./data/finetune"
FINETUNE_SPEAKER_NAME = None
FINETUNE_SOURCE_AUDIO = "vocals"
FINETUNE_CLIP_MIN_SEC = 1.5
FINETUNE_CLIP_MAX_SEC = 11.0
FINETUNE_MIN_TEXT_CHARS = 10
FINETUNE_MAX_TEXT_CHARS = 220
FINETUNE_PADDING_MS = 80
FINETUNE_EVAL_RATIO = 0.1
FINETUNE_MAX_EVAL_SAMPLES = 20
FINETUNE_REFERENCE_CLIPS = 5
FINETUNE_NUM_EPOCHS = 100
FINETUNE_BATCH_SIZE = 8
FINETUNE_GRAD_ACCUM_STEPS = 1
FINETUNE_MAX_AUDIO_SEC = 15
