from pathlib import Path
from types import SimpleNamespace

from src.subtitles import (
    add_subtitles_to_video,
    embed_subtitles_hard,
    generate_ass,
    generate_srt,
    generate_vtt,
)


SEGMENTS = [
    {
        "text": "Привет мир",
        "original_text": "Hello world",
        "start": 1.0,
        "end": 2.5,
    }
]


def test_generate_subtitle_formats(tmp_path: Path) -> None:
    srt_path = generate_srt(SEGMENTS, str(tmp_path / "out.srt"))
    vtt_path = generate_vtt(SEGMENTS, str(tmp_path / "out.vtt"))
    ass_path = generate_ass(SEGMENTS, str(tmp_path / "out.ass"))

    srt = Path(srt_path).read_text(encoding="utf-8")
    vtt = Path(vtt_path).read_text(encoding="utf-8")
    ass = Path(ass_path).read_text(encoding="utf-8-sig")

    assert "00:00:01,000 --> 00:00:02,500" in srt
    assert "00:00:01.000 --> 00:00:02.500" in vtt
    assert "Dialogue:" in ass
    assert "Привет мир" in ass


def test_subtitle_timestamps_do_not_overflow_on_rounding(tmp_path: Path) -> None:
    segments = [
        {
            "text": "Край",
            "original_text": "Edge",
            "start": 1.9996,
            "end": 3599.9999,
        }
    ]

    srt = Path(generate_srt(segments, str(tmp_path / "edge.srt"))).read_text(encoding="utf-8")
    vtt = Path(generate_vtt(segments, str(tmp_path / "edge.vtt"))).read_text(encoding="utf-8")
    ass = Path(generate_ass(segments, str(tmp_path / "edge.ass"))).read_text(encoding="utf-8-sig")

    assert "00:00:02,000 --> 01:00:00,000" in srt
    assert "00:00:02.000 --> 01:00:00.000" in vtt
    assert "0:00:02.00" in ass
    assert "1:00:00.00" in ass


def test_hard_subtitle_embedding_reencodes_visible_video(
    tmp_path: Path,
    monkeypatch,
) -> None:
    commands = []

    def fake_run(cmd, capture_output, text):
        commands.append(cmd)
        return SimpleNamespace(returncode=0, stderr="")

    monkeypatch.setattr("src.subtitles.subprocess.run", fake_run)

    embed_subtitles_hard(
        video_path=str(tmp_path / "video.mp4"),
        subtitle_path=str(tmp_path / "subtitles.ass"),
        output_path=str(tmp_path / "out.mp4"),
    )

    cmd = commands[0]
    assert cmd[cmd.index("-vf") + 1].startswith("ass=")
    assert cmd[cmd.index("-c:v") + 1] == "libx264"
    assert cmd[cmd.index("-pix_fmt") + 1] == "yuv420p"


def test_add_subtitles_defaults_to_hard_output_only(
    tmp_path: Path,
    monkeypatch,
) -> None:
    def fake_soft(video_path, subtitle_path, output_path, language="rus", title="Русский"):
        raise AssertionError("soft subtitles should not be generated by default")

    def fake_hard(video_path, subtitle_path, output_path, video_size="1920x1080"):
        Path(output_path).write_bytes(b"hard")
        return output_path

    monkeypatch.setattr("src.subtitles.embed_subtitles_soft", fake_soft)
    monkeypatch.setattr("src.subtitles.embed_subtitles_hard", fake_hard)

    stale_soft = tmp_path / "subtitles" / "final_video_soft_subs_ru.mp4"
    stale_soft.parent.mkdir(parents=True, exist_ok=True)
    stale_soft.write_bytes(b"stale")

    results = add_subtitles_to_video(
        video_path=str(tmp_path / "final_video.mp4"),
        segments=SEGMENTS,
        output_dir=str(tmp_path / "subtitles"),
        suffix="demo",
    )

    assert "video_soft" not in results
    assert "video_hard" in results
    assert not stale_soft.exists()
